apiVersion: v1
kind: "ConfigMap"
metadata:
  name: "bootstrap-mounted-configmap"
data:
  01_create_databases.sh: |
    #!/bin/bash
    set -e
    clickhouse client -n <<-EOSQL
      CREATE DATABASE IF NOT EXISTS otel;
    EOSQL
  02_create_table.sh: |
    #!/bin/bash
    set -e
    clickhouse client -n <<-EOSQL
      CREATE USER IF NOT EXISTS collector IDENTIFIED BY 'collector' HOST IP '10.0.0.0/8';
      GRANT SELECT, INSERT, UPDATE, DROP, DELETE, ALTER, CREATE ON otel.* TO collector;
      GRANT CREATE DATABASE ON *.* TO collector;
      CREATE USER IF NOT EXISTS grafana IDENTIFIED BY 'grafana' HOST IP '10.0.0.0/8';
      GRANT SELECT ON otel.* TO grafana;
    EOSQL
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "monitoringdb"
  labels:
    application_group: "monitoring"
spec:
  configuration:
    clusters:
      - name: "monitoring"
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: "true"
              volumeMounts:
                - name: bootstrap-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: bootstrap-configmap-volume
              configMap:
                name: bootstrap-mounted-configmap
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
